### PR TITLE
Added create and drop mix tasks

### PR DESCRIPTION
**Pull request by cs-victor-nascimento**
This implements #38.

I moved the tests to separate them from the mix tests. If that is not ok I'll move them back.

There is only one thing that I am not testing: I can't test that it actually destroys the schema. The table shema is always there cause Amnesia.info(:tables) needs Amnesia to be started. @meh if you can think of something here it would be cool.

### CODE REVIEW

**Comment by meh** [comment]
One very hacky way would be to check if the mnesia directory still exists, nothing else comes to mind.

**Comment by cs-victor-nascimento** [comment]
I tried that but the property `:mnesia.system_info(:use_dir)` always returned false to me. Maybe its because the drop tests are using a memory node. Not sure though...

**Comment by meh** [comment]
meh. I'm fine with that test being absent.

I just have some style nits, can you avoid the inline `do:` stuff and remove the empty line after the `do` please?

**Comment by cs-victor-nascimento** [comment]
Sure! Will do it. I'll ping you afterwards.

**Comment by cs-victor-nascimento** [comment]
@meh done.

**Comment by meh** [comment]
Merged, thanks! :panda_face:

**Comment by cs-victor-nascimento** [comment]
No problem! Do you want me to send you a PR updating the README?

**Comment by meh** [comment]
Ah yeah, that would be nice.

**Pull request closed without merging**
